<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/8/20
 * Time: 11:57
 */

class Wine extends ProductLoadTemplate implements IProduct {

    public function getChild($args) {
        return parent::loadData($args[0], 'Wine'); // TODO: Change the autogenerated stub
    }

    public function getList() {
        return [
            ['wine_id'=>'30001','wine_name'=>'茅台','wine_price'=>1200],
            ['wine_id'=>'30002','wine_name'=>'伏特加','wine_price'=>800],
            ['wine_id'=>'30003','wine_name'=>'雪花','wine_price'=>12],
        ];
    }

    public function setClick()
    {
        // TODO: Implement setClick() method.
    }

    public function setLog()
    {
        // TODO: Implement setLog() method.
    }
}