<?php

class userStep1 extends userReg {
    public $step = 'step1';

    public function stepNext(userEntity $user)
    {
        if($user->step == $this->step) {
            echo 'step1<br/>';
            if(isset($_POST['user_name']) && $_POST['user_pass']) {
                $user->user_name = $_POST['user_name'];
                $user->user_pass = $_POST['user_pass'];
            } else {
                // return;
            }
        }

        $getUser = parent::stepNext($user); // TODO: Change the autogenerated stub
        if(isset($getUser) && $getUser) {
            // $_SESSION['user'] = json_encode($getUser);
            $_SESSION['user'] = serialize($getUser);
        }

    }
}