<?php

class userStep2 extends userReg {
    public $step = 'step2';

    public function stepNext(userEntity $user)
    {
        if($user->step == $this->step) {
            echo 'step2<br/>';
            if(isset($_POST['user_phone'])) {
                $user->user_phone = $_POST['user_phone'];
                echo 'user_name='.$user->user_name.'<br/>';
                echo 'user_pass='.$user->user_pass.'<br/>';
                echo 'user_phone='.$user->user_phone.'<br/>';
            } else {
                // return;
            }
        }

        $getUser = parent::stepNext($user); // TODO: Change the autogenerated stub
        if(isset($getUser) && $getUser) {
            // $_SESSION['user'] = json_encode($getUser);
            $_SESSION['user'] = serialize($getUser);
        }

    }
}