<?php

class userStep3 extends userReg {
    public $step = 'step3';

    public function stepNext(userEntity $user)
    {
        if($user->step == $this->step) {
            echo 'step3<br/>';
        }

       /* $getUser = parent::stepNext($user); // TODO: Change the autogenerated stub
        if(isset($getUser) && $getUser) {
            $_SESSION['user'] = json_encode($getUser);
        }*/

    }
}